// Regenerates assets/data/kol-profiles.js from wallets.txt + scripts/data/seed-profiles.json.
//
// scripts/data/seed-profiles.json holds the 257 KOL profiles (481 wallets) originally
// clustered by hand/LLM judgment in the "KOL Index" artifact this app is based on —
// grouping many wallet nicknames (e.g. SVR27;123, SVR4444, SVR67...) under one trader
// identity (e.g. "SVR"). That clustering can't be fully reconstructed by a simple script
// (it merges typos, substrings, translated aliases, etc.), so we treat it as a durable
// seed and only need to reconcile wallets.txt entries that are genuinely new since then.
//
// Run this after editing wallets.txt: node scripts/build-kols.js
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const root = path.join(__dirname, '..');
const wallets = JSON.parse(fs.readFileSync(path.join(root, 'wallets.txt'), 'utf8'));
const seedProfiles = JSON.parse(fs.readFileSync(path.join(__dirname, 'data', 'seed-profiles.json'), 'utf8'));

const seedAddrSet = new Set();
seedProfiles.forEach((p) => p.wallets.forEach((w) => seedAddrSet.add(w.address)));

const newWallets = wallets.filter((w) => !seedAddrSet.has(w.trackedWalletAddress));

// Manually reviewed clusters among the wallets added to wallets.txt after the seed was
// captured (none of them share a root with an existing seed profile — checked by script).
// Keyed by address; anything not listed here becomes its own singleton profile.
const MANUAL_CLUSTERS = [
  { name: 'WhiteWhale', addresses: ['EBxgMjihSYK1UsfsJtNUhYq6RvuzYh5qFzQVfKew79cb', 'ECyvtxvY4KNBt5vfLtdsMrp77mKjL3JD6aha9m3aXBvd'] },
  { name: 'MageArez', addresses: ['9vZ3T6zYJW3mpv1bkmpX3G8aRBM4b8b7iDpDkZXJiVkA', '9agFZUZaRfGjPK2SQn5MSDVwo8yteUogNZwpkhC3uh1V'] },
  { name: 'Fartcoin', addresses: ['F5BwXazdmZjM5wYFZEhf18P9zdg5ZVAyUwwCVrgwfhsd', 'HyYNVYmnFmi87NsQqWzLJhUTPBKQUfgfhdbBa554nMFF'] },
];

function shortId(seedStr) {
  return crypto.createHash('sha1').update(seedStr).digest('hex').slice(0, 10);
}

function seedRelevanceFor(walletCount, hasSquad) {
  const base = 30 + 8 * (walletCount - 1) + (hasSquad ? 20 : 0);
  return Math.max(0, Math.min(100, base));
}

const clusteredAddrs = new Set(MANUAL_CLUSTERS.flatMap((c) => c.addresses));
const newByAddr = new Map(newWallets.map((w) => [w.trackedWalletAddress, w]));

const freshProfiles = [];

MANUAL_CLUSTERS.forEach((c) => {
  const clusterWallets = c.addresses
    .map((addr) => newByAddr.get(addr))
    .filter(Boolean)
    .map((w) => ({ name: w.name, address: w.trackedWalletAddress }));
  if (!clusterWallets.length) return;
  freshProfiles.push({
    id: shortId('cluster:' + c.name),
    name: c.name,
    wallets: clusterWallets,
    squads: [],
    seedRelevance: seedRelevanceFor(clusterWallets.length, false),
  });
});

newWallets
  .filter((w) => !clusteredAddrs.has(w.trackedWalletAddress))
  .forEach((w) => {
    freshProfiles.push({
      id: shortId('single:' + w.trackedWalletAddress),
      name: w.name,
      wallets: [{ name: w.name, address: w.trackedWalletAddress }],
      squads: [],
      seedRelevance: seedRelevanceFor(1, false),
    });
  });

const allProfiles = seedProfiles.concat(freshProfiles);
const totalWallets = allProfiles.reduce((s, p) => s + p.wallets.length, 0);

const out = path.join(root, 'assets', 'data', 'kol-profiles.js');
const banner =
  '// AUTO-GENERATED by scripts/build-kols.js from wallets.txt + scripts/data/seed-profiles.json — do not edit by hand.\n' +
  `// ${allProfiles.length} KOL profiles / ${totalWallets} wallets (${seedProfiles.length} seeded, ${freshProfiles.length} reconciled from new wallets.txt entries).\n` +
  '// Loadable both as a browser <script> (sets window.KOL_PROFILES) and via Node require() (module.exports).\n';
const body =
  `(function () {\n  var KOL_PROFILES = ${JSON.stringify(allProfiles, null, 2)};\n` +
  '  if (typeof window !== "undefined") window.KOL_PROFILES = KOL_PROFILES;\n' +
  '  if (typeof module !== "undefined" && module.exports) module.exports = KOL_PROFILES;\n})();\n';
fs.writeFileSync(out, banner + body);

console.log(`Wrote ${allProfiles.length} profiles / ${totalWallets} wallets to ${path.relative(root, out)}`);
console.log(`  seed: ${seedProfiles.length} profiles / ${seedAddrSet.size} wallets`);
console.log(`  new:  ${freshProfiles.length} profiles / ${newWallets.length} wallets (${MANUAL_CLUSTERS.length} manual clusters)`);
